import { create } from 'zustand'
import type { AppState, AccountInput } from '../lib/types'
import { models } from '../../wailsjs/go/models'

// Polling profile configurations (lobby ms, in-game ms, failure threshold)
// Profiles balance UI responsiveness vs system resource usage
// failureThreshold controls how many empty detections before clearing active account
export const POLLING_PROFILES = {
  instant: {
    name: 'Instant',
    description: 'Real-time updates, more resources',
    lobbyMs: 1000,    // 1s - real-time feel
    inGameMs: 15000,  // 15s - still checks periodically
    failureThreshold: 1, // Clear on first failure for instant feedback
  },
  balanced: {
    name: 'Balanced',
    description: 'Good responsiveness, minimal impact',
    lobbyMs: 5000,    // 5s - responsive enough
    inGameMs: 30000,  // 30s - light touch during gameplay
    failureThreshold: 2, // Tolerate 1 hiccup (10s total)
  },
  eco: {
    name: 'Eco',
    description: 'Minimal resources, slower updates',
    lobbyMs: 15000,   // 15s - background mode
    inGameMs: 60000,  // 60s - near-zero impact
    failureThreshold: 2, // Tolerate 1 hiccup (30s total)
  },
} as const

export type PollingProfile = keyof typeof POLLING_PROFILES
import {
  VaultExists,
  IsUnlocked,
  CreateVault,
  CreateVaultWithHint,
  CreateVaultWithRecoveryPhrase,
  Unlock,
  Lock,
  GetAllAccounts,
  GetGameNetworks,
  GetAllTags,
  GetSettings,
  CreateAccount,
  UpdateAccount,
  DeleteAccount,
  AddTag,
  GetUsername,
  GetStoredUsername,
  GetPasswordHint,
  HasRecoveryPhrase,
  ChangePassword,
  UpdatePasswordHint,
  UpdateSettings,
  GenerateRecoveryPhraseForLegacyUser,
  RegenerateRecoveryPhrase,
  ResetPasswordWithRecoveryPhrase,
  DetectSignedInAccount,
  MatchAndUpdateAccount,
  IsRiotClientRunning,
  IsInGame,
  SetWindowSizeLogin,
  SetWindowSizeMain,
  GetAppVersion,
  CheckForUpdates,
  DownloadAndInstallUpdate,
  OpenReleasePage,
  ConsumePendingRecoveryRotation,
  DetectLegacyVault,
  AdoptLegacyVault,
  ImportVaultFromPath,
  PickVaultFile,
} from '../../wailsjs/go/main/App'
import { providers, storage, updater } from '../../wailsjs/go/models'

interface AppStore {
  // App state
  appState: AppState
  error: string | null

  // User info
  username: string
  storedUsername: string // Pre-filled from vault for login
  passwordHint: string // Password hint displayed on lock screen
  hasRecoveryPhrase: boolean // Whether vault has recovery phrase set

  // Legacy vault recovery — orphaned OpenSmurfManager vault.osm that the
  // rebrand migration left behind (e.g. when both legacy and current dirs
  // already had a vault file). Surfaced on the auth screens so users can
  // adopt it instead of being stuck with an unknown current vault.
  legacyVault: storage.LegacyVaultInfo | null
  isAdoptingLegacy: boolean
  // recentlyAdopted is set to true the moment AdoptLegacyVault returns
  // successfully and cleared on the next successful unlock (or lock). It
  // drives a green "✓ Migrated to Deckstr" confirmation on the unlock
  // screen so the user gets feedback that the swap worked AND that the
  // OpenSmurfManager folder is now gone.
  recentlyAdopted: boolean

  // Recovery phrase state (shown after creation/change)
  pendingRecoveryPhrase: string | null
  showRecoveryPhraseModal: boolean
  requiresPinSetup: boolean // Forces user to reveal PIN before continuing
  // isRotationPhrase is true when the pending phrase was just generated by
  // the v1→v2 security migration rather than by a deliberate user action
  // (create vault / change password / regenerate). The modal copy softens
  // for this case — see RecoveryPhraseModal.
  isRotationPhrase: boolean

  // Data
  accounts: models.Account[]
  gameNetworks: models.GameNetwork[]
  tags: string[]
  settings: models.Settings | null

  // Detection state
  detectedAccount: providers.DetectedAccount | null
  isDetecting: boolean
  riotClientRunning: boolean
  activeAccountId: string | null // Currently signed-in account ID
  isPolling: boolean
  isInGame: boolean // True when user is in active gameplay (pauses LCU polling)
  // Polling reliability state
  _pollInProgress: boolean // Mutex to prevent overlapping polls
  pollingFailures: number // Consecutive failures for backoff
  pollingBackoffMs: number // Current backoff interval

  // Filters
  searchQuery: string
  selectedNetworkId: string | null
  selectedTag: string | null

  // Selected account for editing
  selectedAccountId: string | null

  // Rank sync state
  lastRankSyncTime: number | null // Unix timestamp of last sync
  pendingRankSync: boolean // Sync is queued
  rankSyncError: string | null

  // Update state
  appVersion: string
  updateInfo: updater.UpdateInfo | null
  isCheckingForUpdates: boolean
  showUpdateModal: boolean

  // Actions
  initialize: () => Promise<void>
  createVault: (username: string, password: string, hint?: string) => Promise<boolean>
  unlock: (username: string, password: string) => Promise<boolean>
  lock: () => void
  adoptLegacyVault: () => Promise<boolean>
  importVaultFromFile: () => Promise<{ ok: boolean; cancelled: boolean }>
  changePassword: (currentPassword: string, newPassword: string) => Promise<boolean>
  updatePasswordHint: (hint: string) => Promise<boolean>
  generateRecoveryPhrase: () => Promise<string | null>
  regenerateRecoveryPhrase: (password: string) => Promise<boolean>
  resetPasswordWithRecoveryPhrase: (recoveryPhrase: string, newPassword: string, newHint: string) => Promise<boolean>
  dismissRecoveryPhraseModal: () => void
  clearError: () => void

  // Account actions
  loadAccounts: () => Promise<void>
  addAccount: (account: AccountInput) => Promise<boolean>
  editAccount: (account: AccountInput & { id: string }) => Promise<boolean>
  removeAccount: (id: string) => Promise<boolean>
  selectAccount: (id: string | null) => void

  // Tag actions
  createTag: (tag: string) => Promise<void>

  // Filter actions
  setSearchQuery: (query: string) => void
  setSelectedNetwork: (networkId: string | null) => void
  setSelectedTag: (tag: string | null) => void

  // Detection actions
  detectAndUpdateRanks: () => Promise<string | null>
  checkRiotClient: () => Promise<boolean>
  getPollingIntervals: () => { name: string; description: string; lobbyMs: number; inGameMs: number; failureThreshold: number }
  pollForActiveAccount: () => Promise<void>
  startPolling: () => void
  stopPolling: () => void
  // Rank sync actions
  scheduleRankSync: () => void
  executeRankSync: () => Promise<void>
  startPeriodicRankSync: () => void
  stopPeriodicRankSync: () => void

  // Update actions
  checkForUpdates: () => Promise<void>
  downloadAndInstallUpdate: () => Promise<void>
  openReleasePage: () => Promise<void>
  dismissUpdateModal: () => void
  updateSettings: (settings: models.Settings) => Promise<boolean>

  // Computed
  filteredAccounts: () => models.Account[]
}

export const useAppStore = create<AppStore>((set, get) => ({
  // Initial state
  appState: 'loading',
  error: null,
  username: '',
  storedUsername: '',
  passwordHint: '',
  hasRecoveryPhrase: false,
  legacyVault: null,
  isAdoptingLegacy: false,
  recentlyAdopted: false,
  pendingRecoveryPhrase: null,
  showRecoveryPhraseModal: false,
  requiresPinSetup: false,
  isRotationPhrase: false,
  accounts: [],
  gameNetworks: [],
  tags: [],
  settings: null,
  detectedAccount: null,
  isDetecting: false,
  riotClientRunning: false,
  activeAccountId: null,
  isPolling: false,
  isInGame: false,
  _pollInProgress: false,
  pollingFailures: 0,
  pollingBackoffMs: 5000, // Default, actual value set by polling profile
  lastRankSyncTime: null,
  pendingRankSync: false,
  rankSyncError: null,
  searchQuery: '',
  selectedNetworkId: null,
  selectedTag: null,
  selectedAccountId: null,
  appVersion: '',
  updateInfo: null,
  isCheckingForUpdates: false,
  showUpdateModal: false,

  // Initialize app - check vault state
  initialize: async () => {
    try {
      const exists = await VaultExists()
      const unlocked = await IsUnlocked()

      // Probe for an orphaned OpenSmurfManager vault on every initialize.
      // Cheap (single stat + small JSON parse) and runs even when the
      // current vault is unlocked, so adopting later is one-click.
      let legacyVault: storage.LegacyVaultInfo | null = null
      try {
        legacyVault = await DetectLegacyVault()
      } catch (e) {
        console.warn('Legacy vault detection failed:', e)
      }

      if (unlocked) {
        // Load data
        const [accounts, networks, tags, settings, username] = await Promise.all([
          GetAllAccounts(),
          GetGameNetworks(),
          GetAllTags(),
          GetSettings(),
          GetUsername(),
        ])
        set({
          appState: 'unlocked',
          username,
          accounts: accounts || [],
          gameNetworks: networks || [],
          tags: tags || [],
          settings,
          legacyVault,
        })
        // Resize to main window size
        SetWindowSizeMain()
        // Start polling for active account
        get().startPolling()
      } else if (exists) {
        // Get stored username, password hint, and recovery phrase status for login form
        try {
          const [storedUsername, passwordHint, hasRecovery] = await Promise.all([
            GetStoredUsername(),
            GetPasswordHint(),
            HasRecoveryPhrase(),
          ])
          set({ appState: 'locked', storedUsername, passwordHint: passwordHint || '', hasRecoveryPhrase: hasRecovery, legacyVault })
        } catch {
          set({ appState: 'locked', legacyVault })
        }
      } else {
        set({ appState: 'create', legacyVault })
      }
    } catch (e) {
      set({ error: String(e) })
    }
  },

  // Import a vault from any user-chosen file. Locks the vault first (required
  // by the backend), opens a native file picker, and routes the chosen path
  // through ImportVaultFromPath. On success the app re-runs initialize() so
  // the unlock screen pre-fills the imported username.
  //
  // Returns { ok, cancelled } so callers can distinguish "user cancelled
  // the picker" from "import actually failed".
  importVaultFromFile: async () => {
    set({ error: null })
    let path: string
    try {
      path = await PickVaultFile()
    } catch (e) {
      set({ error: String(e) })
      return { ok: false, cancelled: false }
    }
    if (!path) return { ok: false, cancelled: true }

    try {
      Lock()
    } catch {
      // Best effort — if we couldn't lock cleanly the backend will still
      // refuse the import, surfacing a real error to the user.
    }
    try {
      await ImportVaultFromPath(path)
      await get().initialize()
      return { ok: true, cancelled: false }
    } catch (e) {
      set({ error: String(e) })
      // Re-init anyway so the UI reflects whatever state we ended up in
      // (e.g. locked-out from the just-archived vault).
      await get().initialize()
      return { ok: false, cancelled: false }
    }
  },

  // Adopt the legacy vault: archives the current vault.osm (if any) and
  // installs the legacy bytes at the canonical path, then re-runs initialize
  // so the unlock screen pre-fills the adopted username. Refused by the
  // backend if the vault is currently unlocked.
  adoptLegacyVault: async () => {
    set({ isAdoptingLegacy: true, error: null })
    try {
      // Lock first so the backend's "must be locked" precondition holds even
      // if the user is currently signed into a stub vault.
      try {
        Lock()
      } catch {
        // Lock() is best-effort; the backend will refuse adoption if
        // anything left the in-memory state unlocked.
      }
      await AdoptLegacyVault()
      set({ isAdoptingLegacy: false, legacyVault: null, recentlyAdopted: true })
      await get().initialize()
      return true
    } catch (e) {
      set({ isAdoptingLegacy: false, error: String(e) })
      return false
    }
  },

  // Create new vault with recovery phrase
  createVault: async (username: string, password: string, hint?: string) => {
    try {
      // Always use the new recovery phrase method
      const recoveryPhrase = await CreateVaultWithRecoveryPhrase(username, password, hint || '')

      const [accounts, networks, tags, settings] = await Promise.all([
        GetAllAccounts(),
        GetGameNetworks(),
        GetAllTags(),
        GetSettings(),
      ])
      set({
        appState: 'unlocked',
        username,
        accounts: accounts || [],
        gameNetworks: networks || [],
        tags: tags || [],
        settings,
        hasRecoveryPhrase: true,
        pendingRecoveryPhrase: recoveryPhrase,
        showRecoveryPhraseModal: true,
        requiresPinSetup: true, // Force user to reveal PIN before continuing
        error: null,
      })
      // Resize to main window size
      SetWindowSizeMain()
      // Start polling for active account
      get().startPolling()
      return true
    } catch (e) {
      set({ error: String(e) })
      return false
    }
  },

  // Unlock vault
  unlock: async (username: string, password: string) => {
    try {
      await Unlock(username, password)
      const [accounts, networks, tags, settings] = await Promise.all([
        GetAllAccounts(),
        GetGameNetworks(),
        GetAllTags(),
        GetSettings(),
      ])
      set({
        appState: 'unlocked',
        username,
        accounts: accounts || [],
        gameNetworks: networks || [],
        tags: tags || [],
        settings,
        error: null,
        // Successful sign-in retires the post-adoption notice — its job is
        // done once the user has actually used the migrated credentials.
        recentlyAdopted: false,
      })
      // Resize to main window size
      SetWindowSizeMain()
      // Start polling for active account
      get().startPolling()

      // The Go-side Unlock may have just migrated a v1 vault to v2, which
      // rotates the recovery phrase. Consume the one-shot sidecar first —
      // the old phrase no longer works, so showing the new one is mandatory.
      const rotated = await ConsumePendingRecoveryRotation()
      if (rotated && rotated.present && rotated.phrase) {
        set({
          hasRecoveryPhrase: true,
          pendingRecoveryPhrase: rotated.phrase,
          showRecoveryPhraseModal: true,
          requiresPinSetup: true,
          isRotationPhrase: true,
        })
      } else {
        // No rotation — fall through to the legacy-user check.
        const hasRecovery = await HasRecoveryPhrase()
        if (!hasRecovery) {
          const recoveryPhrase = await GenerateRecoveryPhraseForLegacyUser()
          set({
            hasRecoveryPhrase: true,
            pendingRecoveryPhrase: recoveryPhrase,
            showRecoveryPhraseModal: true,
            requiresPinSetup: true,
            isRotationPhrase: false,
          })
        }
      }

      return true
    } catch (e) {
      set({ error: 'Invalid username or password' })
      return false
    }
  },

  // Lock vault
  lock: () => {
    const currentUsername = get().username
    // Stop polling
    get().stopPolling()
    Lock()
    set({
      appState: 'locked',
      storedUsername: currentUsername, // Pre-fill for next login
      username: '',
      accounts: [],
      tags: [],
      settings: null,
      selectedAccountId: null,
      activeAccountId: null,
      detectedAccount: null,
    })
    // Resize back to login window size
    SetWindowSizeLogin()
  },

  // Change password (returns new recovery phrase)
  changePassword: async (currentPassword: string, newPassword: string) => {
    try {
      const newRecoveryPhrase = await ChangePassword(currentPassword, newPassword)
      set({
        error: null,
        hasRecoveryPhrase: true,
        pendingRecoveryPhrase: newRecoveryPhrase,
        showRecoveryPhraseModal: true,
      })
      return true
    } catch (e) {
      set({ error: String(e) })
      return false
    }
  },

  // Update password hint (for legacy users or changing hint)
  updatePasswordHint: async (hint: string) => {
    try {
      await UpdatePasswordHint(hint)
      set({ passwordHint: hint, error: null })
      return true
    } catch (e) {
      set({ error: String(e) })
      return false
    }
  },

  clearError: () => set({ error: null }),

  // Generate recovery phrase for legacy users (must be unlocked)
  generateRecoveryPhrase: async () => {
    try {
      const recoveryPhrase = await GenerateRecoveryPhraseForLegacyUser()
      set({
        hasRecoveryPhrase: true,
        pendingRecoveryPhrase: recoveryPhrase,
        showRecoveryPhraseModal: true,
        error: null,
      })
      return recoveryPhrase
    } catch (e) {
      set({ error: String(e) })
      return null
    }
  },

  // Regenerate recovery phrase with password verification
  regenerateRecoveryPhrase: async (password: string) => {
    try {
      const recoveryPhrase = await RegenerateRecoveryPhrase(password)
      set({
        hasRecoveryPhrase: true,
        pendingRecoveryPhrase: recoveryPhrase,
        showRecoveryPhraseModal: true,
        error: null,
      })
      return true
    } catch (e) {
      set({ error: String(e) })
      return false
    }
  },

  // Reset password using recovery phrase
  resetPasswordWithRecoveryPhrase: async (recoveryPhrase: string, newPassword: string, newHint: string) => {
    try {
      const newRecoveryPhrase = await ResetPasswordWithRecoveryPhrase(recoveryPhrase, newPassword, newHint)

      // Vault is now unlocked, load data
      const [accounts, networks, tags, settings, username] = await Promise.all([
        GetAllAccounts(),
        GetGameNetworks(),
        GetAllTags(),
        GetSettings(),
        GetUsername(),
      ])

      set({
        appState: 'unlocked',
        username,
        accounts: accounts || [],
        gameNetworks: networks || [],
        tags: tags || [],
        settings,
        hasRecoveryPhrase: true,
        pendingRecoveryPhrase: newRecoveryPhrase,
        showRecoveryPhraseModal: true,
        error: null,
      })

      // Resize to main window size
      SetWindowSizeMain()
      // Start polling for active account
      get().startPolling()

      return true
    } catch (e) {
      set({ error: String(e) })
      return false
    }
  },

  // Dismiss recovery phrase modal (user acknowledged they saved it)
  dismissRecoveryPhraseModal: () => {
    set({
      showRecoveryPhraseModal: false,
      pendingRecoveryPhrase: null,
      requiresPinSetup: false, // User completed PIN setup
      isRotationPhrase: false,
    })
  },

  // Load accounts
  loadAccounts: async () => {
    try {
      const accounts = await GetAllAccounts()
      set({ accounts: accounts || [] })
    } catch (e) {
      set({ error: String(e) })
    }
  },

  // Add account
  addAccount: async (account) => {
    try {
      const created = await CreateAccount(account as any)
      if (created) {
        await get().loadAccounts()
        return true
      }
      return false
    } catch (e) {
      set({ error: String(e) })
      return false
    }
  },

  // Edit account
  editAccount: async (account) => {
    try {
      const updated = await UpdateAccount(account as any)
      if (updated) {
        await get().loadAccounts()
        return true
      }
      return false
    } catch (e) {
      set({ error: String(e) })
      return false
    }
  },

  // Remove account
  removeAccount: async (id) => {
    try {
      await DeleteAccount(id)
      await get().loadAccounts()
      set({ selectedAccountId: null })
      return true
    } catch (e) {
      set({ error: String(e) })
      return false
    }
  },

  selectAccount: (id) => set({ selectedAccountId: id }),

  // Create tag
  createTag: async (tag) => {
    try {
      await AddTag(tag)
      const tags = await GetAllTags()
      set({ tags: tags || [] })
    } catch (e) {
      set({ error: String(e) })
    }
  },

  // Filters
  setSearchQuery: (query) => set({ searchQuery: query }),
  setSelectedNetwork: (networkId) => set({ selectedNetworkId: networkId }),
  setSelectedTag: (tag) => set({ selectedTag: tag }),

  // Detection actions
  checkRiotClient: async () => {
    try {
      const running = await IsRiotClientRunning()
      set({ riotClientRunning: running })
      return running
    } catch {
      set({ riotClientRunning: false })
      return false
    }
  },

  detectAndUpdateRanks: async () => {
    set({ isDetecting: true, error: null })
    try {
      const detected = await DetectSignedInAccount()
      if (!detected) {
        set({ isDetecting: false, detectedAccount: null, activeAccountId: null })
        return null
      }
      set({ detectedAccount: detected })

      // Try to match and update existing account
      const matchedId = await MatchAndUpdateAccount(detected)

      // Reload accounts to get updated data
      await get().loadAccounts()

      set({ isDetecting: false, activeAccountId: matchedId || null, lastRankSyncTime: Date.now() })
      return matchedId || null
    } catch (e) {
      set({ isDetecting: false, error: String(e), activeAccountId: null })
      return null
    }
  },

  // Get polling intervals based on current profile setting
  getPollingIntervals: () => {
    const profile = get().settings?.pollingProfile || 'balanced'
    return POLLING_PROFILES[profile as PollingProfile] || POLLING_PROFILES.balanced
  },

  // Lightweight polling - just checks who's signed in without updating ranks
  pollForActiveAccount: async () => {
    // Mutex: prevent overlapping poll requests
    if (get()._pollInProgress) return
    set({ _pollInProgress: true })

    const intervals = get().getPollingIntervals()

    try {
      // Check if user is in active gameplay - skip LCU polling to avoid any performance impact
      const inGame = await IsInGame()

      if (inGame) {
        // User is in-game: keep current state, use longer polling interval
        set({
          isInGame: true,
          _pollInProgress: false,
          pollingFailures: 0, // Reset failures when in-game (client is working)
          pollingBackoffMs: intervals.inGameMs,
        })
        return
      }

      // Not in-game: continue with LCU check
      set({ isInGame: false })

      const detected = await DetectSignedInAccount()

      // Check if we got a valid detection (has RiotID)
      if (!detected || !detected.RiotID) {
        // Increment failure count for empty detection too
        const failures = get().pollingFailures + 1
        const threshold = intervals.failureThreshold || 2

        // Clear active account after reaching threshold (profile-aware)
        if (failures >= threshold) {
          set({
            detectedAccount: null,
            activeAccountId: null,
            riotClientRunning: false,
            _pollInProgress: false,
            pollingFailures: 0, // Reset after clearing - no backoff on subsequent empty polls
            pollingBackoffMs: intervals.lobbyMs,
          })
        } else {
          // Keep existing state on temporary failures
          set({
            riotClientRunning: false,
            _pollInProgress: false,
            pollingFailures: failures,
          })
        }
        return
      }

      set({ detectedAccount: detected, riotClientRunning: true })

      // Match to existing account without updating ranks (lightweight)
      const { accounts, activeAccountId: previousActiveId, settings, lastRankSyncTime } = get()
      const riotIdLower = detected.RiotID.toLowerCase()
      const matched = accounts.find(acc =>
        acc.riotId?.toLowerCase() === riotIdLower ||
        acc.puuid === detected.PUUID
      )

      const newActiveId = matched?.id || null

      // Check if this is a NEW account detection (different from previous)
      const isNewAccount = newActiveId && newActiveId !== previousActiveId

      set({
        activeAccountId: newActiveId,
        _pollInProgress: false,
        // Reset backoff on success
        pollingFailures: 0,
        pollingBackoffMs: intervals.lobbyMs,
      })

      // Trigger rank sync on new account detection (if auto-sync enabled and cooldown passed)
      if (isNewAccount && settings?.autoRankSync !== false) {
        const cooldown = settings?.rankSyncIntervalMs || 600000
        const now = Date.now()
        if (now - (lastRankSyncTime || 0) >= cooldown) {
          get().scheduleRankSync()
        }
      }
    } catch {
      // Client closed or error - apply exponential backoff
      const intervals = get().getPollingIntervals()
      const failures = get().pollingFailures + 1
      const threshold = intervals.failureThreshold || 2
      // Exponential backoff starting from lobby interval, max 5 minutes
      const backoff = Math.min(intervals.lobbyMs * Math.pow(1.5, failures), 300000)

      // Clear active account after reaching threshold (profile-aware)
      if (failures >= threshold) {
        set({
          detectedAccount: null,
          riotClientRunning: false,
          activeAccountId: null,
          _pollInProgress: false,
          pollingFailures: 0, // Reset after clearing - prevents infinite backoff growth
          pollingBackoffMs: intervals.lobbyMs, // Back to base interval, not exponential
        })
      } else {
        // Keep existing detection state on temporary failures
        set({
          _pollInProgress: false,
          pollingFailures: failures,
          pollingBackoffMs: backoff,
        })
      }
    }
  },

  startPolling: () => {
    // Always clear any existing polling first (handles HMR restarts)
    const existingTimeout = (window as any).__pollingTimeoutId
    if (existingTimeout) {
      clearTimeout(existingTimeout)
      ;(window as any).__pollingTimeoutId = null
    }

    if (get().isPolling) return
    const intervals = get().getPollingIntervals()
    set({ isPolling: true, pollingFailures: 0, pollingBackoffMs: intervals.lobbyMs })

    // Schedule next poll with dynamic backoff
    const schedulePoll = () => {
      const currentBackoff = get().pollingBackoffMs

      const timeoutId = setTimeout(async () => {
        if (!get().isPolling) return

        await get().pollForActiveAccount()

        // Schedule next poll with current backoff value
        if (get().isPolling) {
          schedulePoll()
        }
      }, currentBackoff)

      // Store timeout ID for cleanup
      ;(window as any).__pollingTimeoutId = timeoutId
    }

    // Initial poll immediately
    get().pollForActiveAccount()
    // Then schedule subsequent polls
    schedulePoll()

    // Also start periodic rank sync
    get().startPeriodicRankSync()
  },

  stopPolling: () => {
    set({ isPolling: false })
    const timeoutId = (window as any).__pollingTimeoutId
    if (timeoutId) {
      clearTimeout(timeoutId)
      ;(window as any).__pollingTimeoutId = null
    }
    // Also stop periodic rank sync
    get().stopPeriodicRankSync()
  },

  // Schedule a rank sync with debounce (3 seconds to let client stabilize)
  scheduleRankSync: () => {
    if (get().pendingRankSync) return
    set({ pendingRankSync: true })

    setTimeout(async () => {
      await get().executeRankSync()
      set({ pendingRankSync: false, lastRankSyncTime: Date.now() })
    }, 3000) // 3-second debounce
  },

  // Execute rank sync if conditions are met
  executeRankSync: async () => {
    const { activeAccountId, settings } = get()

    // Skip if no active account or auto-sync disabled
    if (!activeAccountId) return
    if (settings?.autoRankSync === false) return

    try {
      set({ rankSyncError: null })
      await get().detectAndUpdateRanks()
    } catch (e) {
      set({ rankSyncError: e instanceof Error ? e.message : 'Sync failed' })
    }
  },

  // Start periodic rank sync checker (every 60s, respects cooldown)
  startPeriodicRankSync: () => {
    const intervalId = setInterval(() => {
      const { activeAccountId, settings, lastRankSyncTime, pendingRankSync } = get()

      // Skip if no active account, auto-sync disabled, or sync pending
      if (!activeAccountId || settings?.autoRankSync === false || pendingRankSync) return

      // Check cooldown (default 10 min = 600000ms)
      const cooldown = settings?.rankSyncIntervalMs || 600000
      const now = Date.now()
      if (now - (lastRankSyncTime || 0) >= cooldown) {
        get().executeRankSync().then(() => {
          set({ lastRankSyncTime: Date.now() })
        })
      }
    }, 60000) // Check every minute

    ;(window as any).__rankSyncIntervalId = intervalId
  },

  stopPeriodicRankSync: () => {
    const intervalId = (window as any).__rankSyncIntervalId
    if (intervalId) {
      clearInterval(intervalId)
      ;(window as any).__rankSyncIntervalId = null
    }
  },

  // Update actions
  checkForUpdates: async () => {
    set({ isCheckingForUpdates: true })
    try {
      const version = await GetAppVersion()
      set({ appVersion: version })

      const info = await CheckForUpdates()
      if (info && info.available) {
        set({ updateInfo: info, showUpdateModal: true })
      } else {
        set({ updateInfo: info })
      }
    } catch (e) {
      console.error('Failed to check for updates:', e)
    } finally {
      set({ isCheckingForUpdates: false })
    }
  },

  downloadAndInstallUpdate: async () => {
    const { updateInfo } = get()
    if (!updateInfo?.downloadURL) return

    try {
      await DownloadAndInstallUpdate(updateInfo.downloadURL)
      // App will exit and installer will run
    } catch (e) {
      set({ error: `Update failed: ${e}` })
    }
  },

  openReleasePage: async () => {
    const { updateInfo } = get()
    if (!updateInfo?.releaseURL) return

    try {
      await OpenReleasePage(updateInfo.releaseURL)
    } catch (e) {
      console.error('Failed to open release page:', e)
    }
  },

  dismissUpdateModal: () => {
    set({ showUpdateModal: false })
  },

  updateSettings: async (settings: models.Settings) => {
    try {
      const oldProfile = get().settings?.pollingProfile
      await UpdateSettings(settings)
      set({ settings, error: null })

      // Restart polling if profile changed (applies new intervals immediately)
      if (settings.pollingProfile !== oldProfile && get().isPolling) {
        get().stopPolling()
        get().startPolling()
      }

      return true
    } catch (e) {
      set({ error: String(e) })
      return false
    }
  },

  // Filtered accounts
  filteredAccounts: () => {
    const { accounts, searchQuery, selectedNetworkId, selectedTag } = get()

    return accounts.filter(acc => {
      // Network filter
      if (selectedNetworkId && acc.networkId !== selectedNetworkId) {
        return false
      }

      // Tag filter
      if (selectedTag && !acc.tags.includes(selectedTag)) {
        return false
      }

      // Search filter
      if (searchQuery) {
        const query = searchQuery.toLowerCase()
        return (
          acc.displayName.toLowerCase().includes(query) ||
          acc.username.toLowerCase().includes(query) ||
          acc.notes.toLowerCase().includes(query)
        )
      }

      return true
    })
  },
}))
